# Generated by Django 2.2.9 on 2020-01-20 19:24

import askcompany.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_item_photp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='photp',
        ),
        migrations.AddField(
            model_name='item',
            name='photo',
            field=models.ImageField(default='', upload_to=askcompany.utils.uuid_upload_to),
            preserve_default=False,
        ),
    ]
